config/routes.rb
ChicagoStageDirection::Application.routes.draw do
  resources :submissions, :only => [:new, :create, :destroy, :index]

  resources :companies

  resources :auditions

  resources :associates

  root 'auditions#index'

  get "/login" => 'sessions#new'
  get "/logout" => 'sessions#destroy'
  post "/sessions" => 'sessions#create'

  resources :actors

end

app/models/audition.rb
class Audition < ActiveRecord::Base

  belongs_to :company
  has_many :submissions
  has_many :actors, through: :submissions

end

app/controllers/auditions_controller.rb
class AuditionsController < ApplicationController
  before_action :set_audition, only: [:show, :edit, :update, :destroy]

  # GET /auditions
  # GET /auditions.json
  def index
    @auditions = Audition.all.order(:name)
  end

  # GET /auditions/1
  # GET /auditions/1.json
  def show
  end

  # GET /auditions/new
  def new
    @audition = Audition.new
    @companies = Company.all.order(:name)
  end

  # GET /auditions/1/edit
  def edit
    @companies = Company.all.order(:name)
  end

  # POST /auditions
  # POST /auditions.json
  def create
    @audition = Audition.new(audition_params)

    respond_to do |format|
      if @audition.save
        format.html { redirect_to @audition, notice: 'Audition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @audition }
      else
        format.html { render action: 'new' }
        format.json { render json: @audition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auditions/1
  # PATCH/PUT /auditions/1.json
  def update
    respond_to do |format|
      if @audition.update(audition_params)
        format.html { redirect_to @audition, notice: 'Audition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @audition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auditions/1
  # DELETE /auditions/1.json
  def destroy
    @audition.destroy
    respond_to do |format|
      format.html { redirect_to auditions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audition
      @audition = Audition.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def audition_params
      params.require(:audition).permit(:name, :post_date, :audition_date, :description, :company_id, :equity)
    end
end

app/helpers/auditions_helper.rb
module AuditionsHelper
end

app/views/auditions/_form.html.erb
<%= form_for(@audition) do |f| %>
  <% if @audition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@audition.errors.count, "error") %> prohibited this audition from being saved:</h2>

      <ul>
      <% @audition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :post_date %><br>
    <%= f.date_select :post_date %>
  </div>
  <div class="field">
    <%= f.label :audition_date %><br>
    <%= f.text_field :audition_date %>
  </div>
  <div class="field">
    <%= f.label :equity %>
    <%= f.select :equity, "<option>Equity</option><option>Non-Equity</option>".html_safe %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.select "company_id", options_from_collection_for_select(@companies, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auditions/edit.html.erb
<h1>Editing audition</h1>

<%= render 'form' %>

<%= link_to 'Show', @audition %> |
<%= link_to 'Back', auditions_path %>

app/views/auditions/index.html.erb
<div class="container">

  <h3><span class="primary_blue">Chicago Stage Direction</span> is a streamlined app allowing actors to submit materials with a single click. We post new auditions every day, so check back frequently!</h3>

<div class="row">
  <div class="col-md-3">
        <h1 class="right">Auditions <i class="fa fa-arrow-right"></i></h1>
  <ul class="list-group">
  <li class="list-group-item">
    <span class="badge"><%= Audition.all.count %></span>
    All Auditions
  </li>
  <li class="list-group-item">
    <span class="badge"><%= Audition.where(equity: "Equity").count %></span>
    Equity Auditions
  </li>
  <li class="list-group-item">
    <span class="badge"><%= Audition.where(equity: "Non-Equity").count %></span>
    Non-Equity Auditions
  </li>
</ul>
<span class="notice"><%= notice %></span>
  </div>

<div class="col-md-9">
    <% @auditions.each do |audition| %>
    <% company = Company.find_by(id: audition.company_id) %>
        <h2><%= link_to '<i class="fa fa-check"></i> Submit'.html_safe, new_submission_url(audition_id: audition.id), class: "btn btn-primary" %>  <%= company.name %>: <%= link_to audition.name, audition, class: "link_fix" %></h2>
        <% if audition.equity == "Equity" %>
        <p class="primary_blue"><i class="fa fa-star"></i> <span class="bold"><%= audition.equity %></span></p>
        <% else %>
        <p class="primary_blue"><i class="fa fa-star-o"></i> <span class="bold"><%= audition.equity %></span></p>
        <% end %>
        <span class="bold">Audition Date:</span> <%= audition.audition_date %><br>
        <%= audition.description %><br>
  <% end %>
  </div>
</div>

<br>
<br>

app/views/auditions/new.html.erb
<h1>New audition</h1>

<%= render 'form' %>

<%= link_to 'Back', auditions_path %>

app/views/auditions/show.html.erb
<%= link_to '<i class="fa fa-arrow-left"></i> Back'.html_safe, :back, class: "link_fix" %>

<p id="notice"><%= notice %></p>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to @audition.company.name, company_url(@audition.company), class: "link_fix" %></h3>
  </div>
  <div class="panel-body">
<h2 class="name"><%= @audition.name %></h2>
  <div class="col-md-3">
    <%= image_tag(@audition.company.logo, width: "250") %>
  </div>
  <div class="col-md-9">
<p><span class="bold">Posted:</span> <%= @audition.post_date %></p>
<p><span class="bold">Audition date:</span> <%= @audition.audition_date %></p>
          <% if @audition.equity == "Equity" %>
          <p class="primary_blue"><i class="fa fa-star"></i> <span class="bold"><%= @audition.equity %></span></p>
          <% else %>
          <p class="primary_blue"><i class="fa fa-star-o"></i> <span class="bold"><%= @audition.equity %></span></p>
          <% end %>

<p><%= @audition.description %></p>

<% if session[:associate_id] %>
  <% associate = Associate.find_by(id: session[:associate_id]) %>
  <% if associate.company_id == @audition.company.id %>
  <%= link_to '<i class="fa fa-list-ol"></i> Submissions'.html_safe, submissions_url(audition_id: @audition.id), class: "btn btn-primary" %>
  <%= link_to '<i class="fa fa-pencil"></i> Edit Audition'.html_safe, edit_audition_path(@audition), class: "btn btn-primary" %>
  <%= link_to '<i class="fa fa-trash-o"></i> Delete Audition'.html_safe, @audition, method: :delete, data: { confirm: 'Are you sure you want to delete this audition? This action cannot be reversed.' }, class: "btn btn-primary" %>
  <% end %>
<% end %>
<br>
<br>

<% unless session[:associate_id] %>
<%= link_to 'Submit', new_submission_url(audition_id: @audition.id), class: "btn btn-primary" %>
<% end %>


<br>
<br>
<br>
</div>
</div>
</div>