config/routes.rb
ChicagoStageDirection::Application.routes.draw do
  resources :submissions, :only => [:new, :create, :destroy, :index]

  resources :companies

  resources :auditions

  resources :associates

  root 'auditions#index'

  get "/login" => 'sessions#new'
  get "/logout" => 'sessions#destroy'
  post "/sessions" => 'sessions#create'

  resources :actors

end

app/models/associate.rb
class Associate < ActiveRecord::Base

  has_many :auditions, through: :company
  has_many :submissions, through: :auditions
  has_one :company

  validates_presence_of :name, :title, :company_id, :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  has_secure_password

end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
  before_action :set_associate, only: [:show, :edit, :update, :destroy]
  before_action :confirm_associate, only: [:show, :edit, :update, :destroy]

  # GET /associates
  # GET /associates.json
  def index
    @associates = Associate.all
  end

  # GET /associates/1
  # GET /associates/1.json
  def show
    @company = Company.find_by(id: @associate.company_id)
    @auditions = @company.auditions
  end

  # GET /associates/new
  def new
    @associate = Associate.new
    @companies = Company.all.order(:name)
  end

  # GET /associates/1/edit
  def edit
  end

  # POST /associates
  # POST /associates.json
  def create
    @associate = Associate.new(associate_params)

    respond_to do |format|
      if @associate.save
        session[:associate_id] = @associate.id
        format.html { redirect_to @associate, notice: 'Associate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @associate }
      else
        format.html { render action: 'new' }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associates/1
  # PATCH/PUT /associates/1.json
  def update
    respond_to do |format|
      if @associate.update(associate_params)
        format.html { redirect_to @associate, notice: 'Associate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associates/1
  # DELETE /associates/1.json
  def destroy
    @associate.destroy
    respond_to do |format|
      format.html { redirect_to associates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associate
      @associate = Associate.find(params[:id])
    end

    def confirm_associate
      unless session[:associate_id] && @associate && session[:associate_id] == @associate.id
          flash[:error] = "Please access one of your own pages"
          redirect_to root_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def associate_params
      params.require(:associate).permit(:name, :title, :company_id, :email, :password, :password_confirmation)
    end
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/views/associates/_form.html.erb
<%= form_for(@associate) do |f| %>
  <% if @associate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@associate.errors.count, "error") %> prohibited this associate from being saved:</h2>

      <ul>
      <% @associate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.select "company_id", options_from_collection_for_select(@companies, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/associates/edit.html.erb
<h1>Editing associate</h1>

<%= render 'form' %>

<%= link_to 'Show', @associate %> |
<%= link_to 'Back', associates_path %>

app/views/associates/new.html.erb
<h1>New associate</h1>

<%= render 'form' %>

<%= link_to 'Back', associates_path %>

app/views/associates/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <%= link_to '<i class="fa fa-arrow-left"></i> Back'.html_safe, :back, class: "link_fix" %>
    <h1 class="primary_blue name"><%= @associate.name %></h1>
    <h3><%= @associate.email %></h3>
    <br>
    <%= link_to '<i class="fa fa-magic"></i> New Audition'.html_safe, new_audition_path(company_id: @company.id), class: "btn btn-primary" %>
    <%= link_to '<i class="fa fa-pencil"></i> Edit Profile'.html_safe, edit_associate_path(@associate), class: "btn btn-primary" %>
  </div>

  <div class="col-md-8">
    <br>
    <h2>Companies</h2>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title title"><span class="bold">Title:</span> <%= @associate.title %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <h4><%= @company.name %></h4>
            <a href="/companies/#{@company.id}"><%= image_tag(@company.logo, :width => 180) %></a>
          </div>
          <div class="col-md-8">
            <h2>Active Auditions:</h2>
              <ul>
              <% @auditions.each do |audition| %>
              <li><h4><%= link_to audition.name, audition_url(audition), class: "btn btn-default" %></h4></li>
              <% end %>
              </ul>
          </div>

      </div>
  </div>
</div>
</div>
</div>